"""Vulture whitelist — the audited baseline for `vulture infrastructure/acquisition` (REQ-098 tooling).

Run dead-code sweeps as:

    vulture infrastructure/acquisition .vulture_whitelist.py

so the output is ONLY findings newer than this baseline. The 2026-08-17 audit (see the
`refactor: prune three genuinely-dead symbols` commit) classified all 162 raw findings; the three
genuinely dead ones were REMOVED, so everything listed here is one of:

  * FastAPI route handlers — reached via the `@app.<method>` decorator (79 of them);
  * SQLAlchemy ORM mapped columns/classes — reached via the mapper, incl. the precious
    `GateMode` table;
  * symbols referenced from tests, `infrastructure/scripts`, `tools/`, or the console's
    static JS/HTML — reachable, just not from `infrastructure/acquisition` itself;
  * deliberate keeps: callerless recovery/backfill entry points (`backfill_requests`,
    `import_status_json`, `latest_receipt`, `tally_json`, `get_domain`, …) and
    documentation-by-constant (`MODEL_WINDOWS_FETCHED`, bumped on every #809 catalog refresh).

Maintenance rules:
  * A NEW vulture finding is a decision, not a nuisance: prove it reachable (route/ORM/tests/JS)
    or deliberately kept, THEN add it here with that justification implicit in this header's
    classes — or delete the code. Never append to silence.
  * After deleting code, regenerate to drop stale entries:
        vulture --make-whitelist infrastructure/acquisition > .vulture_whitelist.py
    then restore this header. (Stale entries are harmless to vulture but lie to readers.)

This file is never imported; the bare names below are vulture's whitelist syntax, not code.
"""
benchmark_district_ids  # unused function (infrastructure/acquisition/common/benchmark.py:155)
is_benchmark_district  # unused function (infrastructure/acquisition/common/benchmark.py:165)
_.remaining_run  # unused method (infrastructure/acquisition/common/budget.py:114)
CalibrationEvent  # unused class (infrastructure/acquisition/common/calibration.py:42)
agreed  # unused variable (infrastructure/acquisition/common/calibration.py:56)
capture_path  # unused variable (infrastructure/acquisition/common/calibration.py:62)
sweep_worst_slice  # unused function (infrastructure/acquisition/common/calibration.py:126)
PROVENANCE_FIELDS  # unused variable (infrastructure/acquisition/common/config_loader.py:18)
tally_json  # unused variable (infrastructure/acquisition/common/discovered_domain.py:31)
tally_json  # unused variable (infrastructure/acquisition/common/discovered_domain.py:49)
_.tally_json  # unused attribute (infrastructure/acquisition/common/discovered_domain.py:97)
get_domain  # unused function (infrastructure/acquisition/common/discovered_domain.py:104)
fingerprints_json  # unused variable (infrastructure/acquisition/common/district_status.py:66)
import_status_json  # unused function (infrastructure/acquisition/common/district_status.py:342)
GateMode  # unused class (infrastructure/acquisition/common/gate_mode.py:39)
effective_gate_mode  # unused function (infrastructure/acquisition/common/gate_mode.py:77)
MODEL_WINDOWS_FETCHED  # unused variable (infrastructure/acquisition/common/model_families.py:64)
data_root_is_default  # unused function (infrastructure/acquisition/common/paths.py:69)
latest_receipt  # unused function (infrastructure/acquisition/common/receipts.py:137)
primary_bands_for  # unused function (infrastructure/acquisition/common/school_sampling.py:206)
charter_lookup  # unused function (infrastructure/acquisition/common/school_sampling.py:796)
tree  # unused function (infrastructure/acquisition/process_governance/server.py:178)
save_label  # unused function (infrastructure/acquisition/process_governance/server.py:282)
reset_labels  # unused function (infrastructure/acquisition/process_governance/server.py:344)
split_record  # unused function (infrastructure/acquisition/process_governance/server.py:402)
stage5_districts  # unused function (infrastructure/acquisition/process_governance/server.py:495)
stage5_facets  # unused function (infrastructure/acquisition/process_governance/server.py:636)
detector_weights  # unused function (infrastructure/acquisition/process_governance/server.py:654)
discovery_policy_get  # unused function (infrastructure/acquisition/process_governance/server.py:780)
discovery_policy_set  # unused function (infrastructure/acquisition/process_governance/server.py:809)
discovered_domain_decide  # unused function (infrastructure/acquisition/process_governance/server.py:837)
exclusions_view  # unused function (infrastructure/acquisition/process_governance/server.py:912)
data_years  # unused function (infrastructure/acquisition/process_governance/server.py:925)
gate_mode_list  # unused function (infrastructure/acquisition/process_governance/server.py:939)
gate_mode_set  # unused function (infrastructure/acquisition/process_governance/server.py:947)
mode_stability_get  # unused function (infrastructure/acquisition/process_governance/server.py:964)
mode_stability_toggle  # unused function (infrastructure/acquisition/process_governance/server.py:974)
exploration_audit_status  # unused function (infrastructure/acquisition/process_governance/server.py:992)
followup_list  # unused function (infrastructure/acquisition/process_governance/server.py:1011)
followup_create  # unused function (infrastructure/acquisition/process_governance/server.py:1026)
followup_resolve  # unused function (infrastructure/acquisition/process_governance/server.py:1053)
views_list  # unused function (infrastructure/acquisition/process_governance/server.py:1069)
views_save  # unused function (infrastructure/acquisition/process_governance/server.py:1078)
views_delete  # unused function (infrastructure/acquisition/process_governance/server.py:1101)
serve_file  # unused function (infrastructure/acquisition/process_governance/server.py:1124)
queue_list  # unused function (infrastructure/acquisition/process_governance/server.py:1161)
queue_create  # unused function (infrastructure/acquisition/process_governance/server.py:1167)
queue_get  # unused function (infrastructure/acquisition/process_governance/server.py:1296)
queue_roster_spine  # unused function (infrastructure/acquisition/process_governance/server.py:1305)
queue_edit  # unused function (infrastructure/acquisition/process_governance/server.py:1335)
queue_approve  # unused function (infrastructure/acquisition/process_governance/server.py:1375)
queue_reopen  # unused function (infrastructure/acquisition/process_governance/server.py:1394)
queue_abandon  # unused function (infrastructure/acquisition/process_governance/server.py:1410)
queue_candidates  # unused function (infrastructure/acquisition/process_governance/server.py:1434)
fidelity_triage  # unused function (infrastructure/acquisition/process_governance/server.py:1485)
attribution_card  # unused function (infrastructure/acquisition/process_governance/server.py:1555)
discover_status  # unused function (infrastructure/acquisition/process_governance/server.py:1575)
discover_run  # unused function (infrastructure/acquisition/process_governance/server.py:1617)
capture_status  # unused function (infrastructure/acquisition/process_governance/server.py:1686)
capture_run  # unused function (infrastructure/acquisition/process_governance/server.py:1698)
capture_retry  # unused function (infrastructure/acquisition/process_governance/server.py:1740)
process_status  # unused function (infrastructure/acquisition/process_governance/server.py:1894)
process_run  # unused function (infrastructure/acquisition/process_governance/server.py:1907)
handoff_preview  # unused function (infrastructure/acquisition/process_governance/server.py:2128)
handoff_dispatch  # unused function (infrastructure/acquisition/process_governance/server.py:2149)
handoff_list  # unused function (infrastructure/acquisition/process_governance/server.py:2196)
handoff_detail  # unused function (infrastructure/acquisition/process_governance/server.py:2216)
dispatch_list  # unused function (infrastructure/acquisition/process_governance/server.py:2266)
dispatch_create  # unused function (infrastructure/acquisition/process_governance/server.py:2275)
dispatch_get  # unused function (infrastructure/acquisition/process_governance/server.py:2285)
dispatch_candidates  # unused function (infrastructure/acquisition/process_governance/server.py:2294)
dispatch_edit  # unused function (infrastructure/acquisition/process_governance/server.py:2308)
dispatch_freeze  # unused function (infrastructure/acquisition/process_governance/server.py:2391)
dispatch_abandon  # unused function (infrastructure/acquisition/process_governance/server.py:2419)
extract_run_status  # unused function (infrastructure/acquisition/process_governance/server.py:2450)
extract_run  # unused function (infrastructure/acquisition/process_governance/server.py:2456)
handoff_councils  # unused function (infrastructure/acquisition/process_governance/server.py:2511)
handoff_inspect  # unused function (infrastructure/acquisition/process_governance/server.py:2518)
extract_districts  # unused function (infrastructure/acquisition/process_governance/server.py:2574)
extract_district  # unused function (infrastructure/acquisition/process_governance/server.py:2660)
aggregate_districts  # unused function (infrastructure/acquisition/process_governance/server.py:2760)
aggregate_withheld  # unused function (infrastructure/acquisition/process_governance/server.py:2814)
aggregate_district_detail  # unused function (infrastructure/acquisition/process_governance/server.py:2880)
aggregate_override  # unused function (infrastructure/acquisition/process_governance/server.py:2900)
aggregate_exclude  # unused function (infrastructure/acquisition/process_governance/server.py:2944)
aggregate_exclude_restore  # unused function (infrastructure/acquisition/process_governance/server.py:2980)
aggregate_human_add  # unused function (infrastructure/acquisition/process_governance/server.py:3002)
aggregate_human_add_remove  # unused function (infrastructure/acquisition/process_governance/server.py:3067)
aggregate_slot_assign  # unused function (infrastructure/acquisition/process_governance/server.py:3087)
aggregate_slot_assign_remove  # unused function (infrastructure/acquisition/process_governance/server.py:3156)
aggregate_recover_band  # unused function (infrastructure/acquisition/process_governance/server.py:3186)
aggregate_send_backs  # unused function (infrastructure/acquisition/process_governance/server.py:3203)
aggregate_send_back_route  # unused function (infrastructure/acquisition/process_governance/server.py:3212)
aggregate_decision  # unused function (infrastructure/acquisition/process_governance/server.py:3270)
extract_request_review  # unused function (infrastructure/acquisition/process_governance/server.py:3335)
followup_autoflow_status  # unused function (infrastructure/acquisition/process_governance/server.py:3412)
extract_compose_followup_preview  # unused function (infrastructure/acquisition/process_governance/server.py:3491)
extract_compose_followup  # unused function (infrastructure/acquisition/process_governance/server.py:3505)
filter_compose_zero_yield  # unused function (infrastructure/acquisition/process_governance/server.py:3533)
extract_execute  # unused function (infrastructure/acquisition/process_governance/server.py:3554)
backfill_requests  # unused function (infrastructure/acquisition/process_governance/stage7_run.py:1298)
project_root  # unused variable (infrastructure/acquisition/stage1_queue/queue_batch.py:44)
OUT_DIR  # unused variable (infrastructure/acquisition/stage1_queue/queue_batch.py:50)
run_wave2  # unused function (infrastructure/acquisition/stage2_discover/discover_stage2.py:333)
finish_from_wave1  # unused function (infrastructure/acquisition/stage2_discover/headless.py:219)
_disk_doc_count  # unused function (infrastructure/acquisition/stage4_process/headless.py:119)
winning_sources  # unused function (infrastructure/acquisition/stage4_process/headless.py:125)
canonical_invariant_violations  # unused function (infrastructure/acquisition/stage5_filter/build_signals.py:592)
repair_canonical_invariant  # unused function (infrastructure/acquisition/stage5_filter/build_signals.py:606)
migrate_labels_v21  # unused function (infrastructure/acquisition/stage5_filter/build_signals.py:1007)
current_artifact  # unused function (infrastructure/acquisition/stage5_filter/config_artifact.py:182)
EVENT_CONFIDENCE_SOURCE  # unused variable (infrastructure/acquisition/stage5_filter/detectors.py:362)
calibrate_against_census  # unused function (infrastructure/acquisition/stage5_filter/exploration_live.py:143)
floor_satisfied  # unused function (infrastructure/acquisition/stage5_filter/harness.py:57)
Label  # unused class (infrastructure/acquisition/stage5_filter/models.py:22)
flags_json  # unused variable (infrastructure/acquisition/stage5_filter/models.py:31)
ClusterSplit  # unused class (infrastructure/acquisition/stage5_filter/models.py:42)
directive  # unused variable (infrastructure/acquisition/stage5_filter/models.py:59)
resolved_at  # unused variable (infrastructure/acquisition/stage5_filter/models.py:62)
SavedView  # unused class (infrastructure/acquisition/stage5_filter/models.py:65)
config_json  # unused variable (infrastructure/acquisition/stage5_filter/models.py:72)
ConfigPointer  # unused class (infrastructure/acquisition/stage5_filter/models.py:76)
state_json  # unused variable (infrastructure/acquisition/stage5_filter/models.py:90)
shadow_evaluate  # unused function (infrastructure/acquisition/stage5_filter/promotion_flow.py:33)
actuate  # unused function (infrastructure/acquisition/stage5_filter/promotion_flow.py:73)
record_episode  # unused function (infrastructure/acquisition/stage5_filter/promotion_flow.py:119)
evictable  # unused function (infrastructure/acquisition/stage5_filter/promotion_pointers.py:79)
prune  # unused function (infrastructure/acquisition/stage5_filter/promotion_pointers.py:86)
active_versions  # unused function (infrastructure/acquisition/stage5_filter/promotion_pointers.py:98)
read_artifact  # unused function (infrastructure/acquisition/stage5_filter/promotion_pointers.py:136)
total_usd  # unused variable (infrastructure/acquisition/stage6_handoff/models.py:30)
cost_provenance  # unused variable (infrastructure/acquisition/stage6_handoff/models.py:31)
council_ids  # unused variable (infrastructure/acquisition/stage6_handoff/models.py:42)
n_reps_skipped  # unused variable (infrastructure/acquisition/stage7_extract/models.py:47)
n_calls  # unused variable (infrastructure/acquisition/stage7_extract/models.py:49)
n_judge_calls  # unused variable (infrastructure/acquisition/stage7_extract/models.py:50)
n_errors  # unused variable (infrastructure/acquisition/stage7_extract/models.py:51)
gross_minutes  # unused variable (infrastructure/acquisition/stage7_extract/models.py:73)
models_json  # unused variable (infrastructure/acquisition/stage7_extract/models.py:75)
applies_to  # unused variable (infrastructure/acquisition/stage7_extract/models.py:86)
campus_names_json  # unused variable (infrastructure/acquisition/stage7_extract/models.py:89)
identity_json  # unused variable (infrastructure/acquisition/stage7_extract/models.py:96)
detail_json  # unused variable (infrastructure/acquisition/stage7_extract/models.py:98)
source_file  # unused variable (infrastructure/acquisition/stage7_extract/models.py:101)
altitude  # unused variable (infrastructure/acquisition/stage7_extract/models.py:121)
params_json  # unused variable (infrastructure/acquisition/stage7_extract/models.py:125)
reviewed_by  # unused variable (infrastructure/acquisition/stage7_extract/models.py:129)
reviewed_at  # unused variable (infrastructure/acquisition/stage7_extract/models.py:130)
review_note  # unused variable (infrastructure/acquisition/stage7_extract/models.py:131)
executed_at  # unused variable (infrastructure/acquisition/stage7_extract/models.py:136)
_.was_billed  # unused property (infrastructure/acquisition/stage7_extract/openrouter.py:183)
mode_val  # unused variable (infrastructure/acquisition/stage8_aggregate/aggregate.py:57)
aggregate_district  # unused function (infrastructure/acquisition/stage8_aggregate/aggregate.py:72)
facts_fingerprint  # unused variable (infrastructure/acquisition/stage8_aggregate/models.py:35)
receipt_json  # unused variable (infrastructure/acquisition/stage8_aggregate/models.py:36)
exclusion_id  # unused variable (infrastructure/acquisition/stage8_aggregate/models.py:58)
added_id  # unused variable (infrastructure/acquisition/stage8_aggregate/models.py:85)
source_url  # unused variable (infrastructure/acquisition/stage8_aggregate/models.py:92)
assignment_id  # unused variable (infrastructure/acquisition/stage8_aggregate/models.py:123)
